version: 1.0.7
slug: matterbridge
name: Matterbridge
description: Populate your Home Assistant instance as Matter Bridge
url: https://github.com/t0bst4r/matterbridge-home-assistant-addon
homeassistant: 2024.1.0
homeassistant_api: true
host_network: true
# image: ghcr.io/t0bst4r/matterbridge-home-assistant-addon/{arch}
init: false
arch:
  - aarch64
  - amd64
  - armv7
webui: http://[HOST]:[PORT:8283]/
map:
  - addon_config:rw
options:
  include_domains: []
  include_patterns: []
  exclude_domains: []
  exclude_patterns: []
  plugins: []
schema:
  include_domains:
    - str?
  include_patterns:
    - str?
  exclude_domains:
    - str?
  exclude_patterns:
    - str?
  plugins:
    - str?
